version: 2
updates:
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: daily
    time: "13:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: io.dropwizard.metrics:metrics-core
    versions:
    - 4.1.17
    - 4.1.18
    - 4.1.19
  - dependency-name: org.mockito:mockito-core
    versions:
    - 3.7.7
    - 3.8.0
  - dependency-name: org.apache.commons:commons-lang3
    versions:
    - "3.11"
  - dependency-name: org.apache.avro:avro-maven-plugin
    versions:
    - 1.10.1
  - dependency-name: io.dropwizard:dropwizard-testing
    versions:
    - 2.0.13
    - 2.0.19
  - dependency-name: io.dropwizard:dropwizard-core
    versions:
    - 2.0.13
    - 2.0.19
  - dependency-name: io.dropwizard:dropwizard-auth
    versions:
    - 2.0.13
    - 2.0.19
  - dependency-name: io.dropwizard:dropwizard-assets
    versions:
    - 2.0.13
    - 2.0.19
  - dependency-name: org.scala-lang:scala-library
    versions:
    - 2.13.4
  - dependency-name: org.apache.avro:avro
    versions:
    - 1.10.1
  - dependency-name: org.apache.commons:commons-configuration2
    versions:
    - "2.7"
  - dependency-name: javax.xml.ws:jaxws-api
    versions:
    - 2.3.1
  - dependency-name: javax.annotation:javax.annotation-api
    versions:
    - 1.3.2
